
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Role'
export type * from './models/Permission'
export type * from './models/OAuthClient'
export type * from './models/OAuthAuthorizationCode'
export type * from './models/OAuthAccessToken'
export type * from './models/OAuthRefreshToken'
export type * from './models/Task'
export type * from './commonInputTypes'