name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-and-push-image:
    uses: revisium/revisium-actions/.github/workflows/docker-build.yml@184b609dcbc1e23f14021141f29226d4e6a0f1ac # v0.3.6
    with:
      image_name: ${{ github.event.repository.name }}
      context: .
      dockerfile: docker/Dockerfile
      emit_latest_tag: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
